/**
 * Interview Orchestration Pipeline
 *
 * Dispatches an AI-conducted phone interview via the configured voice provider.
 * Unlike cold calls (executeCall in phone.ts), interviews use:
 *   - Conversation-mode prompts (not linear scripts)
 *   - Longer max durations (10-30 min vs 2-5 min)
 *   - Separate assistant/agent IDs (optional — for provider-side config)
 *   - Recording consent handling
 *
 * Flow:
 *   1. generateInterviewGuide() → InterviewGuide
 *   2. conductInterview() → triggers voice call (this file)
 *   3. Webhook receives transcript → processInterviewResult() (analyze-interview.ts)
 */

import { client } from '../config.js';
import { memory } from '../lib/memory.js';
import { CALL_CONFIG, INTERVIEW_CONFIG } from '../config/prospecting.config.js';
import { createHubSpotFollowUpTask } from '../delivery/hubspot-deliver.js';
import { workspace } from '../lib/workspace.js';
import { logger } from '../lib/logger.js';
import { getInterviewCount, incrementInterviewCount } from '../lib/capacity-store.js';
import { buildElevenLabsOutboundCallPayload } from '../lib/voice-provider-payloads.js';
import type { InterviewGuide, InterviewPurpose } from '../types.js';

const log = logger.child({ pipeline: 'conduct-interview' });

export interface InterviewSendResult {
  callId: string;
  provider: string;
  phone: string;
  purpose: InterviewPurpose;
}

function getRemainingInterviewCapacity(): number {
  return Math.max(0, INTERVIEW_CONFIG.dailyLimit - getInterviewCount());
}

/**
 * Trigger an AI phone interview via the configured voice provider.
 */
export async function conductInterview(
  guide: InterviewGuide,
  contactId: string,
): Promise<InterviewSendResult> {
  if (!INTERVIEW_CONFIG.enabled) {
    throw new Error('Interview module is not enabled. Set INTERVIEW_ENABLED=true');
  }

  if (getRemainingInterviewCapacity() <= 0) {
    log.warn('Interview daily limit reached', { limit: INTERVIEW_CONFIG.dailyLimit });
    throw new Error('Interview daily limit reached');
  }

  const provider = INTERVIEW_CONFIG.provider;
  let callId = '';

  // Create a HubSpot task for CRM tracking
  await createInterviewTask(guide, contactId);

  if (provider === 'bland-ai') {
    callId = await triggerBlandAiInterview(guide);
  } else if (provider === 'vapi') {
    callId = await triggerVapiInterview(guide);
  } else if (provider === 'elevenlabs') {
    callId = await triggerElevenLabsInterview(guide);
  } else {
    throw new Error(`Unsupported interview provider: ${provider}`);
  }

  incrementInterviewCount();

  // Record in workspace
  await workspace.addMessageSent(guide.email, {
    channel: 'call',
    subject: `Interview: ${guide.contactName} — ${guide.purpose}`,
    bodyPreview: `${guide.opening}`.substring(0, 200),
    step: 0, // Interviews don't follow sequence steps
    angle: guide.purpose,
    sentBy: 'outreach-agent',
    status: 'delivered',
  });

  // Memorize
  await memory.save({
    email: guide.email,
    content: [
      `[INTERVIEW INITIATED — ${guide.purpose.toUpperCase()}]`,
      `Date: ${new Date().toISOString()}`,
      `Contact: ${guide.contactName} (${guide.contactTitle})`,
      `Phone: ${guide.phone}`,
      `Provider: ${provider}`,
      `Target Duration: ${guide.targetDurationMins} minutes`,
      `Topics: ${guide.topics.map((t) => t.topic).join(', ')}`,
    ].join('\n'),
    enhanced: true,
    tags: ['interview', 'initiated', `purpose:${guide.purpose}`, `provider:${provider}`],
  });

  log.info('Interview initiated', {
    email: guide.email,
    purpose: guide.purpose,
    provider,
    phone: guide.phone,
    callId,
  });

  return { callId, provider, phone: guide.phone, purpose: guide.purpose };
}

/**
 * Create a HubSpot task for the interview.
 */
async function createInterviewTask(
  guide: InterviewGuide,
  contactId: string,
): Promise<void> {
  const ownerId = process.env.HUBSPOT_OWNER_ID || '';
  if (!ownerId) {
    log.warn('No HUBSPOT_OWNER_ID — skipping interview task creation');
    return;
  }

  const topicList = guide.topics
    .map((t, i) => `  ${i + 1}. ${t.topic} (${t.maxMinutes} min)\n     Q: ${t.primaryQuestion}`)
    .join('\n\n');

  await createHubSpotFollowUpTask({
    contactId,
    ownerId,
    subject: `Interview: ${guide.contactName} — ${guide.purpose.replace('_', ' ')}`,
    body: [
      `**AI Interview: ${guide.contactName}**`,
      `**Phone:** ${guide.phone}`,
      `**Purpose:** ${guide.purpose.replace('_', ' ')}`,
      `**Duration:** ${guide.targetDurationMins} min`,
      '',
      '━━━ TOPICS ━━━',
      '',
      topicList,
      '',
      '━━━ KNOWLEDGE GAPS ━━━',
      '',
      guide.knowledgeGaps.map((g) => `  • ${g}`).join('\n'),
      '',
      '---',
      'Generated by Revenue OS Interview Module.',
    ].join('\n'),
    priority: 'HIGH',
    taskType: 'CALL',
  });
}

/**
 * Trigger interview via Bland.ai.
 * Uses `task` field with the full AI interviewer prompt (conversation mode).
 */
async function triggerBlandAiInterview(guide: InterviewGuide): Promise<string> {
  const { blandApiKey, blandPhoneNumberId } = CALL_CONFIG;
  if (!blandApiKey) throw new Error('BLAND_API_KEY required for bland-ai provider');

  const response = await fetch('https://api.bland.ai/v1/calls', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'authorization': blandApiKey,
    },
    body: JSON.stringify({
      phone_number: guide.phone,
      from: blandPhoneNumberId || undefined,
      task: guide.aiInterviewerPrompt,
      first_sentence: guide.opening,
      wait_for_greeting: true,
      record: true,
      max_duration: INTERVIEW_CONFIG.maxDurationMins,
      model: 'enhanced', // Use enhanced model for longer, nuanced conversations
      language: 'en-US',
      ...(INTERVIEW_CONFIG.webhookUrl && { webhook: INTERVIEW_CONFIG.webhookUrl }),
      metadata: {
        email: guide.email,
        purpose: guide.purpose,
        contactName: guide.contactName,
        type: 'interview',
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`Bland.ai API error: ${response.status} ${await response.text()}`);
  }

  const data = await response.json() as any;
  log.info('Bland.ai interview triggered', { callId: data.call_id, phone: guide.phone });
  return data.call_id || `bland-interview-${Date.now()}`;
}

/**
 * Trigger interview via Vapi.
 * Vapi's conversation model handles dynamic dialogue well — recommended for interviews.
 */
async function triggerVapiInterview(guide: InterviewGuide): Promise<string> {
  const { vapiApiKey } = CALL_CONFIG;
  if (!vapiApiKey) throw new Error('VAPI_API_KEY required for vapi provider');

  const assistantId = INTERVIEW_CONFIG.vapiInterviewAssistantId || CALL_CONFIG.vapiAssistantId;

  const response = await fetch('https://api.vapi.ai/calls', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${vapiApiKey}`,
    },
    body: JSON.stringify({
      phoneNumber: guide.phone,
      assistantId: assistantId || undefined,
      assistantOverrides: {
        firstMessage: guide.opening,
        model: {
          messages: [
            {
              role: 'system',
              content: guide.aiInterviewerPrompt,
            },
          ],
        },
        // Longer silence timeout for interviews — people think before answering
        silenceTimeoutSeconds: 10,
        maxDurationSeconds: INTERVIEW_CONFIG.maxDurationMins * 60,
      },
      customData: {
        email: guide.email,
        purpose: guide.purpose,
        contactName: guide.contactName,
        type: 'interview',
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`Vapi API error: ${response.status} ${await response.text()}`);
  }

  const data = await response.json() as any;
  log.info('Vapi interview triggered', { callId: data.id, phone: guide.phone });
  return data.id || `vapi-interview-${Date.now()}`;
}

/**
 * Trigger interview via ElevenLabs Conversational AI.
 */
async function triggerElevenLabsInterview(guide: InterviewGuide): Promise<string> {
  const { elevenlabsApiKey, elevenlabsPhoneNumberId } = CALL_CONFIG;
  const agentId = INTERVIEW_CONFIG.elevenlabsInterviewAgentId || CALL_CONFIG.elevenlabsAgentId;

  if (!elevenlabsApiKey) throw new Error('ELEVENLABS_API_KEY required for elevenlabs provider');
  if (!agentId) throw new Error('ELEVENLABS_AGENT_ID or ELEVENLABS_INTERVIEW_AGENT_ID required');
  if (!elevenlabsPhoneNumberId) throw new Error('ELEVENLABS_PHONE_NUMBER_ID required');

  const response = await fetch('https://api.elevenlabs.io/v1/convai/twilio/outbound-call', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'xi-api-key': elevenlabsApiKey,
    },
    body: JSON.stringify({
      agent_id: agentId,
      agent_phone_number_id: elevenlabsPhoneNumberId,
      to_number: guide.phone,
      conversation_initiation_client_data: {
        dynamic_variables: {
          email: guide.email,
          purpose: guide.purpose,
          contact_name: guide.contactName,
          contact_title: guide.contactTitle,
          opener: guide.opening,
          script: guide.aiInterviewerPrompt,
          type: 'interview',
        },
      },
      call_recording_enabled: true,
    }),
  });

  if (!response.ok) {
    throw new Error(`ElevenLabs API error: ${response.status} ${await response.text()}`);
  }

  const data = await response.json() as any;
  log.info('ElevenLabs interview triggered', {
    conversationId: data.conversation_id,
    phone: guide.phone,
  });
  return data.conversation_id || data.callSid || `11labs-interview-${Date.now()}`;
}

export { getRemainingInterviewCapacity };
