import { Client as HubSpotClient } from '@hubspot/api-client';
import { client } from '../config.js';
import { sendViaGmail } from './gmail.js';
import { sendViaSendGrid } from './sendgrid.js';
import { sendViaSmartlead } from './smartlead.js';
import { EMAIL_DELIVERY_CONFIG, MANUAL_HUBSPOT_CONFIG } from '../config/prospecting.config.js';
import type { GeneratedEmail } from '../types.js';
import { logger } from '../lib/logger.js';

if (!process.env.HUBSPOT_ACCESS_TOKEN) {
  throw new Error('Missing required environment variable: HUBSPOT_ACCESS_TOKEN');
}

const hubspot = new HubSpotClient({ accessToken: process.env.HUBSPOT_ACCESS_TOKEN });

export async function createHubSpotEmail(generated: GeneratedEmail, contactId: string) {
  await hubspot.crm.objects.emails.basicApi.create({
    properties: {
      hs_timestamp: new Date().toISOString(),
      hs_email_direction: 'EMAIL',
      hs_email_subject: generated.subject,
      hs_email_text: generated.bodyText,
      hs_email_html: generated.bodyHtml,
      hs_email_status: 'SENT',
    },
    associations: [
      {
        to: { id: contactId },
        types: [{ associationCategory: 'HUBSPOT_DEFINED', associationTypeId: 198 }],
      },
    ],
  });
}

export async function createHubSpotTask(generated: GeneratedEmail, contactId: string, ownerId: string) {
  await hubspot.crm.objects.tasks.basicApi.create({
    properties: {
      hs_timestamp: new Date().toISOString(),
      hs_task_subject: `Review & Send: Email ${generated.step} to ${generated.email}`,
      hs_task_body: [
        `**Subject:** ${generated.subject}`,
        `**Angle:** ${generated.angle}`,
        `**Email Body:**`,
        generated.bodyText,
        '',
        `---`,
        `Generated by AI Prospecting Agent. Review and send.`,
      ].join('\n'),
      hs_task_status: 'NOT_STARTED',
      hs_task_priority: 'HIGH',
      hubspot_owner_id: ownerId,
      hs_task_type: 'EMAIL',
    },
    associations: [
      {
        to: { id: contactId },
        types: [{ associationCategory: 'HUBSPOT_DEFINED', associationTypeId: 204 }],
      },
    ],
  });
}

/**
 * Create a follow-up task in HubSpot based on reply analysis.
 * Used by the reply analyzer for positive, question, and referral replies.
 */
export async function createHubSpotFollowUpTask(params: {
  contactId: string;
  ownerId: string;
  subject: string;
  body: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  taskType: 'CALL' | 'EMAIL' | 'TODO';
}) {
  try {
    await hubspot.crm.objects.tasks.basicApi.create({
      properties: {
        hs_timestamp: new Date().toISOString(),
        hs_task_subject: params.subject,
        hs_task_body: params.body,
        hs_task_status: 'NOT_STARTED',
        hs_task_priority: params.priority,
        hubspot_owner_id: params.ownerId,
        hs_task_type: params.taskType,
      },
      associations: [
        {
          to: { id: params.contactId },
          types: [{ associationCategory: 'HUBSPOT_DEFINED', associationTypeId: 204 }],
        },
      ],
    });
    logger.info('Created HubSpot task', { subject: params.subject });
  } catch (err) {
    logger.error('Failed to create HubSpot task', { error: err instanceof Error ? err.message : String(err) });
  }
}

/**
 * Send an email via the configured provider and record the outcome.
 *
 * Provider is selected via EMAIL_PROVIDER env var:
 *   smartlead      — Smartlead managed mailboxes (default)
 *   sendgrid       — SendGrid with your own sender domain
 *   gmail          — Gmail API with Google Workspace accounts
 *   manual-hubspot — No send; creates a HubSpot task for human review
 *
 * All providers:
 *   - Record the email (sent or draft) in Personize memory so the next
 *     sequence step knows what was already written and which angles were used.
 *   - Log the activity in HubSpot (sent email record or review task).
 */
export async function sendAndLog(generated: GeneratedEmail, contactId: string) {
  const log = logger.child({ pipeline: 'hubspot-deliver' });
  const provider = EMAIL_DELIVERY_CONFIG.provider;

  // ── manual-hubspot: draft path ─────────────────────────────────
  if (provider === 'manual-hubspot') {
    const ownerId = MANUAL_HUBSPOT_CONFIG.ownerId;
    if (!ownerId) throw new Error('Missing HUBSPOT_OWNER_ID — required for manual-hubspot provider');

    // Create HubSpot task for human review
    await createHubSpotTask(generated, contactId, ownerId);

    // Memorize as DRAFT — sequence reads this to know the step was generated
    // but will not advance past this step until a SENT record appears
    await client.memory.memorize({
      email: generated.email,
      content: [
        `[OUTREACH DRAFT \u2014 Email ${generated.step}]`,
        `Date: ${new Date().toISOString()}`,
        `Subject: ${generated.subject}`,
        `Angle: ${generated.angle}`,
        `Provider: manual-hubspot`,
        `Status: Pending human review in HubSpot`,
        `Body: ${generated.bodyText}`,
      ].join('\n'),
      enhanced: true,
      tags: ['generated', 'outreach', `sequence:email-${generated.step}`, 'draft', 'manual-hubspot'],
    });

    log.info('Manual draft created', { email: generated.email, step: generated.step, provider });
    return { messageId: '', senderEmail: '' };
  }

  // ── send paths ─────────────────────────────────────────────────
  let messageId = '';
  let senderEmail = '';
  let providerMeta = '';

  if (provider === 'smartlead') {
    const result = await sendViaSmartlead(generated);
    messageId = result.messageId;
    senderEmail = result.senderEmail;
    providerMeta = `Smartlead Lead ID: ${result.leadId}`;

  } else if (provider === 'sendgrid') {
    const response = await sendViaSendGrid(generated);
    messageId = response[0]?.headers?.['x-message-id'] || '';
    senderEmail = process.env.SENDER_EMAIL || '';
    providerMeta = `SendGrid Message ID: ${messageId}`;

  } else {
    // gmail (default fallback)
    const result = await sendViaGmail(generated);
    messageId = result.messageId;
    senderEmail = result.senderEmail;
    providerMeta = `Gmail Message ID: ${result.messageId} | Thread ID: ${result.threadId}`;
  }

  // Log sent email activity in HubSpot
  await createHubSpotEmail(generated, contactId);

  // Memorize as SENT — sequence reads this to advance to the next step
  await client.memory.memorize({
    email: generated.email,
    content: [
      `[OUTREACH SENT \u2014 Email ${generated.step}]`,
      `Date: ${new Date().toISOString()}`,
      `Subject: ${generated.subject}`,
      `Angle: ${generated.angle}`,
      `Provider: ${provider}`,
      `Sender: ${senderEmail}`,
      providerMeta,
      `Body: ${generated.bodyText}`,
    ].join('\n'),
    enhanced: true,
    tags: ['generated', 'outreach', `sequence:email-${generated.step}`, 'sent', `provider:${provider}`, `sender:${senderEmail}`],
  });

  log.info('Email sent', { email: generated.email, step: generated.step, provider, senderEmail });
  return { messageId, senderEmail };
}
