import { Client as HubSpotClient } from '@hubspot/api-client';
import { AssociationSpecAssociationCategoryEnum as EmailAssociationCategoryEnum } from '@hubspot/api-client/lib/codegen/crm/objects/emails/models/AssociationSpec.js';
import { AssociationSpecAssociationCategoryEnum as TaskAssociationCategoryEnum } from '@hubspot/api-client/lib/codegen/crm/objects/tasks/models/AssociationSpec.js';
import { sendViaGmail, sendGmailReply, type ThreadContext } from './gmail.js';
import { sendViaSmartlead } from './smartlead.js';
import { EMAIL_DELIVERY_CONFIG, MANUAL_HUBSPOT_CONFIG, GMAIL_CONFIG } from '../config/prospecting.config.js';
import type { GeneratedEmail } from '../types.js';
import { logger } from '../lib/logger.js';

if (!process.env.HUBSPOT_ACCESS_TOKEN) {
  throw new Error('Missing required environment variable: HUBSPOT_ACCESS_TOKEN');
}

const hubspot = new HubSpotClient({ accessToken: process.env.HUBSPOT_ACCESS_TOKEN });

export async function createHubSpotEmail(generated: GeneratedEmail, contactId: string) {
  await hubspot.crm.objects.emails.basicApi.create({
    properties: {
      hs_timestamp: new Date().toISOString(),
      hs_email_direction: 'EMAIL',
      hs_email_subject: generated.subject,
      hs_email_text: generated.bodyText,
      hs_email_html: generated.bodyHtml,
      hs_email_status: 'SENT',
    },
    associations: [
      {
        to: { id: contactId },
        types: [{ associationCategory: EmailAssociationCategoryEnum.HubspotDefined, associationTypeId: 198 }],
      },
    ],
  });
}

export async function createHubSpotTask(generated: GeneratedEmail, contactId: string, ownerId: string) {
  await hubspot.crm.objects.tasks.basicApi.create({
    properties: {
      hs_timestamp: new Date().toISOString(),
      hs_task_subject: `Review & Send: Email ${generated.step} to ${generated.email}`,
      hs_task_body: [
        `**Subject:** ${generated.subject}`,
        `**Angle:** ${generated.angle}`,
        `**Email Body:**`,
        generated.bodyText,
        '',
        `---`,
        `Generated by Revenue OS. Review and send.`,
      ].join('\n'),
      hs_task_status: 'NOT_STARTED',
      hs_task_priority: 'HIGH',
      hubspot_owner_id: ownerId,
      hs_task_type: 'EMAIL',
    },
    associations: [
      {
        to: { id: contactId },
        types: [{ associationCategory: TaskAssociationCategoryEnum.HubspotDefined, associationTypeId: 204 }],
      },
    ],
  });
}

/**
 * Create a follow-up task in HubSpot based on reply analysis.
 * Used by the reply analyzer for positive, question, and referral replies.
 */
export async function createHubSpotFollowUpTask(params: {
  contactId: string;
  ownerId: string;
  subject: string;
  body: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  taskType: 'CALL' | 'EMAIL' | 'TODO';
}) {
  try {
    await hubspot.crm.objects.tasks.basicApi.create({
      properties: {
        hs_timestamp: new Date().toISOString(),
        hs_task_subject: params.subject,
        hs_task_body: params.body,
        hs_task_status: 'NOT_STARTED',
        hs_task_priority: params.priority,
        hubspot_owner_id: params.ownerId,
        hs_task_type: params.taskType,
      },
      associations: [
        {
          to: { id: params.contactId },
          types: [{ associationCategory: TaskAssociationCategoryEnum.HubspotDefined, associationTypeId: 204 }],
        },
      ],
    });
    logger.info('Created HubSpot task', { subject: params.subject });
  } catch (err) {
    logger.error('Failed to create HubSpot task', { error: err instanceof Error ? err.message : String(err) });
  }
}

/**
 * Send an email via the configured provider and record the outcome.
 *
 * Provider is selected via EMAIL_PROVIDER env var:
 *   smartlead      — Smartlead managed mailboxes (default)
 *   sendgrid       — SendGrid with your own sender domain
 *   gmail          — Gmail API with Google Workspace accounts
 *   manual-hubspot — No send; creates a HubSpot task for human review
 *
 * All providers:
 *   - Log the activity in HubSpot (sent email record or review task).
 *   - Return { messageId, senderEmail, isDraft } so callers can branch on draft status.
 *   - Outreach state is tracked by workspace.addMessageSent() in the caller (outreach-sequence.ts).
 */
export async function sendAndLog(generated: GeneratedEmail, contactId: string) {
  const log = logger.child({ pipeline: 'hubspot-deliver' });
  const provider = EMAIL_DELIVERY_CONFIG.provider;

  // ── manual-hubspot: draft path ─────────────────────────────────
  if (provider === 'manual-hubspot') {
    const ownerId = MANUAL_HUBSPOT_CONFIG.ownerId;
    if (!ownerId) throw new Error('Missing HUBSPOT_OWNER_ID — required for manual-hubspot provider');

    // Create HubSpot task for human review
    await createHubSpotTask(generated, contactId, ownerId);

    log.info('Manual draft created', { email: generated.email, step: generated.step, provider });
    return { messageId: '', senderEmail: '', isDraft: true };
  }

  // ── send paths ─────────────────────────────────────────────────
  let messageId = '';
  let senderEmail = '';

  if (provider === 'smartlead') {
    const result = await sendViaSmartlead(generated);
    messageId = result.messageId;
    senderEmail = result.senderEmail;

  } else if (provider === 'sendgrid') {
    const { sendViaSendGrid } = await import('./sendgrid.js');
    const response = await sendViaSendGrid(generated);
    messageId = response[0]?.headers?.['x-message-id'] || '';
    senderEmail = process.env.SENDER_EMAIL || '';

  } else {
    // gmail (default fallback)
    const result = await sendViaGmail(generated);
    messageId = result.messageId;
    senderEmail = result.senderEmail;
  }

  // Log sent email activity in HubSpot
  await createHubSpotEmail(generated, contactId);

  log.info('Email sent', { email: generated.email, step: generated.step, provider, senderEmail });
  return { messageId, senderEmail, isDraft: false };
}

/**
 * Send a reply in an existing email thread and log to HubSpot.
 *
 * Routes to the right provider's reply method, passing thread context
 * (In-Reply-To, References, threadId) so the reply appears in the
 * same conversation across all email clients.
 *
 * Provider priority:
 *   1. SMTP via IMAP account (if smtpAccountId provided — universal, zero vendor)
 *   2. Gmail API (if configured — native threadId support)
 *   3. Fallback to regular sendAndLog (loses threading for some providers)
 */
export async function sendReplyAndLog(
  generated: GeneratedEmail,
  contactId: string,
  thread: ThreadContext & {
    /** ID of the IMAP account to send from via SMTP. If set, SMTP is used. */
    smtpAccountId?: string;
  },
) {
  const log = logger.child({ pipeline: 'hubspot-deliver' });
  const provider = EMAIL_DELIVERY_CONFIG.provider;

  let messageId = '';
  let senderEmail = '';

  // ── Option 1: SMTP via linked IMAP account (universal) ─────────
  if (thread.smtpAccountId) {
    try {
      const { imapAccounts } = await import('../lib/imap-accounts.js');
      const { smtpDelivery } = await import('./smtp.js');
      const account = await imapAccounts.getById(thread.smtpAccountId);

      if (account && account.sendingEnabled && account.smtpHost) {
        const result = await smtpDelivery.sendReply(
          account,
          { to: generated.email, subject: generated.subject, bodyHtml: generated.bodyHtml, bodyText: generated.bodyText },
          { inReplyTo: thread.inReplyTo || '', references: thread.references || [], originalSubject: thread.originalSubject },
        );
        messageId = result.messageId;
        senderEmail = result.senderEmail;

        await createHubSpotEmail(generated, contactId);
        log.info('Reply sent via SMTP', { email: generated.email, account: account.email, inReplyTo: thread.inReplyTo });
        return { messageId, senderEmail, isDraft: false };
      }
    } catch (err) {
      log.warn('SMTP reply failed, falling through to other providers', {
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  // ── Option 2: Gmail API (native threading) ─────────────────────
  if (provider === 'gmail' || (!provider && GMAIL_CONFIG.senders.length > 0)) {
    const result = await sendGmailReply(generated, thread);
    messageId = result.messageId;
    senderEmail = result.senderEmail;

    await createHubSpotEmail(generated, contactId);
    log.info('Reply sent via Gmail API', { email: generated.email, threadId: thread.threadId });
    return { messageId, senderEmail, isDraft: false };
  }

  // ── Option 3: Fallback to regular send ─────────────────────────
  log.info('Reply via non-threading provider — thread context may not be preserved', { provider });
  return sendAndLog(generated, contactId);
}

/**
 * Send a new email via SMTP using an IMAP account.
 * Use this when EMAIL_PROVIDER is not set but the user has IMAP accounts with SMTP enabled.
 */
export async function sendViaSmtp(
  generated: GeneratedEmail,
  smtpAccountId: string,
) {
  const { imapAccounts } = await import('../lib/imap-accounts.js');
  const { smtpDelivery } = await import('./smtp.js');

  const account = await imapAccounts.getById(smtpAccountId);
  if (!account || !account.sendingEnabled || !account.smtpHost) {
    throw new Error(`SMTP not available for account ${smtpAccountId}`);
  }

  return smtpDelivery.send(account, {
    to: generated.email,
    subject: generated.subject,
    bodyHtml: generated.bodyHtml,
    bodyText: generated.bodyText,
  });
}
